### PR TITLE
Delete room if last user leaves

### PR DESCRIPTION
**Pull request by Mollie-S**
What is implemented:
- when a user is leaving a room the server checks whether the room becomes orphanated. If yes, the room is removed. If it was a public room the user is pushed to the default room

as a side:
-  AddMessageDto was implemented as we need to validate any information that goes to the server

### CODE REVIEW

**Comment by Mollie-S** [comment]
> 

Weird, I cannot reproduce both comment behaviours. Liveshare today?

**Comment by ergunirem** [comment]
I'm up for a liveshare. I also cannot reproduce Aileen's comments. On the other hand, what I have is that when there is a public room and the last person leaves, room is immediately invisible on that users page but all the other users still see it until they refresh the page.

**Comment by Mollie-S** [comment]
> I'm up for a liveshare. I also cannot reproduce Aileen's comments. On the other hand, what I have is that when there is a public room and the last person leaves, room is immediately invisible on that users page but all the other users still see it until they refresh the page.

ah, ok, a nice update. But tbh I doubt it's reasonable to update ALL the users' lists. Won't it be too much overload for the server then?

**Comment by ergunirem** [comment]
> > I'm up for a liveshare. I also cannot reproduce Aileen's comments. On the other hand, what I have is that when there is a public room and the last person leaves, room is immediately invisible on that users page but all the other users still see it until they refresh the page.
> 
> ah, ok, a nice update. But tbh I doubt it's reasonable to update ALL the users' lists. Won't it be too much overload for the server then?

It might overload but not sure which implementation makes more sense and how much it would overload given the scale of our project its only a few rooms and a few users.

**Review by ergunirem — APPROVED** [review]

**Comment by aprilmayjune135** [comment]
We have test it again together and things works great now.
It can be merged.

**Pull request merged**
