### PR TITLE
Room input validation

### PR DESCRIPTION
**Pull request by Mollie-S**
What has been added:
- frontend:
   - new room names are validated on frontend (you are unable to leave the name empty or enter more than 64 characters);
   - error messages notify user about the input problem;
   
- backend:
Server side validation is also added. WsException is caught. To test it you can:
    - delete the client validation in `InputText` component on `views/CreateRoom.vue` for a while (remove `maxlength="64"`)  and try to type a name exceeding 64 characters. 
    - try to type sth other than alphanumeric with space inside (space alone or the name starting or ending with a space is not allowed) ==> you should see the error message

### CODE REVIEW

**Comment by ergunirem** [comment]
The error msg says It cannot start or end with a whitespace but I was able to create name: "irem    " room and I also had one room called name: "irem" (with no whitespace in the end).  In this case, it appears like the room name is not unique. (practically it is unique since it has a space but it appears the same in room listing view.
Screen Shot 2022-06-08 at 3 41 49 PM

**Comment by ergunirem** [comment]
As mentioned when I remove the max-length from the InputText, I get this error msg: This name is too long. Please create a shorter one.

**Comment by Mollie-S** [comment]
> The error msg says It cannot start or end with a whitespace but I was able to create name: "irem " room and I also had one room called name: "irem" (with no whitespace in the end). In this case, it appears like the room name is not unique. (practically it is unique since it has a space but it appears the same in r Screen Shot 2022-06-08 at 3 41 54 PM oom listing view.

Fixed [in this commit](https://github.com/42-jkoers/ft_transcendence/pull/70/commits/1d15ab3b58497012da8842435af8a0d2ce8f7e07)

**Comment by ergunirem** [comment]
I checked the latest commit. It does indeed solve the problem with room name ending with whitespace. You can merge it.

**Pull request merged**
