### PR TITLE
116 chat direct messages logic implementation

### PR DESCRIPTION
**Pull request by Mollie-S**
What is implemented:
- user can send a direct message to another user from the chat;
- the 'display name' is added to the room object which is the same as the room name for other rooms and reflects the second user username;
- the room name is generated by uuid on server;
- user cannot leave the private room at the moment. Might be fixed later.

What has been changed:
-[removed "message' button from the user's own profile card](https://github.com/42-jkoers/ft_transcendence/issues/134)
- updated the icons marking the user is inside the room
- bug in User - UserToRoom relationship

### CODE REVIEW

**Comment by Mollie-S** [comment]
Will close this one as some implementation is changed in another PR

**Review by ergunirem — CHANGES_REQUESTED** [review]
When I right click on a user and send DM, I see my own name as the room name. Is it that what it supposed to look like? See the pictures below. Xxu send the DM and room name is also xxu in xxu's own connection.

Screenshot 2022-06-27 at 16 09 37
393e.png)

**Comment by ergunirem** [comment]
I checked the code as well. The fetching sockets part looks solid and fetches both sides socket's and joins them into this DM room with its name.

**Review by aprilmayjune135 — APPROVED** [review]
We've looked at the code together, tested together (for multiple times), it can be merged.

**Comment by ergunirem** [comment]
I might add this as an issue but I realized that when I deregister one side of the DM, the room name changes to this but I really think this is a minor issue not a priority
Screenshot 2022-06-27 at 18 01 42

**Pull request merged**
